title: Resumo Daniel M. oliveira
author: danielmoliveira
email: daniel@danielmoliveira.net
description: > # this means to ignore newlines until "baseurl:"
  Resume Developer Daniel M. Oliveira, more than 18 years experience, Biztalk, .NET Core SQL Server, Azure, AWS, Microsoft
  Sales Force
  
theme: minima

# social links
twitter_username: danielmoliveira # DO NOT include the @ character, or else the build will fail!
github_username:  danielmoliveira # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
